name: Release Build

on:
  push:
  pull_request:

jobs:
  build:
    name: build checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build
        run: python script/build_extension.py

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./release
